2020-05-06 02:58:40,880 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-06 18:11:21,440 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 02:51:54,928 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 02:53:38,613 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:03:01,936 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:03:52,820 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:04:00,225 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:04:19,440 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:32:03,311 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:32:16,921 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:32:24,902 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:32:39,153 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:46:45,511 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-07 03:52:52,881 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-09 01:37:38,296 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-09 01:57:39,514 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-09 02:03:57,278 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 19:50:49,747 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 19:51:40,134 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 19:51:41,994 ERROR: Exception on / [GET] [in D:\py project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\py project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\py project\abc\app\main\routes.py", line 23, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all)
  File "D:\py project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\py project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\py project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\py project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\py project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\py project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\py project\abc\app\templates\base.html", line 97, in block "content"
    {% block current_app_content %}{% endblock %}
  File "D:\py project\abc\app\templates\ez.html", line 38, in block "current_app_content"
    <h3><a href="{{ url_for(one.url) }}"><font color="#000000">{{ one.title }}</font></a></h3>
  File "D:\py project\abc\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\py project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\py project\abc\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "D:\py project\abc\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.ucc'. Did you mean 'main.ucceva' instead?
2020-05-10 19:52:27,551 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 19:52:31,004 ERROR: Exception on / [GET] [in D:\py project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\py project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\py project\abc\app\main\routes.py", line 23, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all)
  File "D:\py project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\py project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\py project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\py project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\py project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\py project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\py project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\py project\abc\app\templates\base.html", line 97, in block "content"
    {% block current_app_content %}{% endblock %}
  File "D:\py project\abc\app\templates\ez.html", line 38, in block "current_app_content"
    <h3><a href="{{ url_for(one.url) }}"><font color="#000000">{{ one.title }}</font></a></h3>
  File "D:\py project\abc\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\py project\abc\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\py project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\py project\abc\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "D:\py project\abc\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.ucc'. Did you mean 'main.ucceva' instead?
2020-05-10 19:53:09,380 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 19:53:20,905 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 23:18:38,836 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-10 23:22:54,558 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 01:02:48,948 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 01:03:21,826 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 21:56:14,573 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 21:57:46,056 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 21:58:52,244 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 21:59:16,216 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
2020-05-12 22:03:42,283 INFO: Microblog startup [in D:\py project\abc\app\__init__.py:74]
