2020-05-11 22:43:17,676 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 23, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 97, in block "content"
    {% block current_app_content %}{% endblock %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 32, in block "current_app_content"
    {% for one in all %}
TypeError: 'News' object is not iterable
2020-05-11 22:43:46,392 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-11 22:43:47,741 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 23, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 97, in block "content"
    {% block current_app_content %}{% endblock %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 32, in block "current_app_content"
    {% for one in all %}
TypeError: 'News' object is not iterable
2020-05-11 22:43:57,756 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-11 22:43:58,946 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 23, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 97, in block "content"
    {% block current_app_content %}{% endblock %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 32, in block "current_app_content"
    {% for one in all %}
TypeError: 'News' object is not iterable
