2020-05-14 02:49:40,506 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 25, in ez
    techv2 = Tech.query.filter(Tech.picture_name != tech.picture_name).order_by(func.random()).limit(2)
AttributeError: 'BaseQuery' object has no attribute 'picture_name'
2020-05-14 02:50:47,195 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:57:19,459 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:57:38,519 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:58:13,900 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:58:54,525 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:58:55,611 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 31, in ez
    techv2 = Tech.query.filter(Tech.picture_name != tech_data[0] and tech_data[1]).order_by(func.random()).limit(2)
  File "<string>", line 2, in filter
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1816, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4591, in _expression_literal_as_text
    return _literal_as_text(element)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4614, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4600, in _literal_as
    return text_fallback(element)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4641, in _no_text_coercion
    util.raise_(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'intel10.png' should be explicitly declared as text('intel10.png')
2020-05-14 02:59:35,536 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 02:59:36,908 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 31, in ez
    techv2 = Tech.query.filter(Tech.picture_name != str(tech_data[0]) and str(tech_data[1])).order_by(func.random()).limit(2)
  File "<string>", line 2, in filter
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1816, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4591, in _expression_literal_as_text
    return _literal_as_text(element)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4614, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4600, in _literal_as
    return text_fallback(element)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4641, in _no_text_coercion
    util.raise_(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'ipxs.jpg' should be explicitly declared as text('ipxs.jpg')
2020-05-14 03:02:00,133 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:02:33,995 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:04:49,993 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:07:34,081 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:09:22,336 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:09:58,262 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:11:14,783 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:11:51,147 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:14:39,166 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:14:40,670 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 29, in ez
    techv2 = Tech.query.filter(~Tech.picture_name.in_(tech_data[0], tech_data[1])).order_by(func.random()).limit(2)
TypeError: in_() takes 2 positional arguments but 3 were given
2020-05-14 03:16:08,741 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:17:08,279 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:18:58,037 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:24:30,171 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:32:53,322 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
