2020-05-18 18:05:25,502 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:06:07,732 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:09:44,864 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:14:07,022 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:14:40,925 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:17:47,041 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:20:00,349 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:21:18,147 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:26:02,400 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:26:03,926 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 34, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all, tech=tech, hot=hot, network=network,
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 100, in block "content"
    {% block current_app_content %}{% endblock %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 64, in block "current_app_content"
    <a href="{{ url_for(news.TF.url, picture=news.picture_name, content=news.TF.title) }}" class="table-card text-center">
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.tfb' with values ['content', 'picture']. Did you forget to specify values ['table']?
2020-05-18 18:27:00,176 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:28:00,146 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:28:36,660 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:30:11,962 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-18 18:30:13,048 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 34, in ez
    return render_template('ez.html', title=_('E-Zone'), all=all, tech=tech, hot=hot, network=network,
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\base.html", line 100, in block "content"
    {% block current_app_content %}{% endblock %}
  File "C:\Users\s2905\Desktop\EA Project\abc\app\templates\ez.html", line 123, in block "current_app_content"
    <a href="{{ url_for(news.VDO.url) }}" class="table-card text-center">
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.ccmask'. Did you mean 'main.omask' instead?
2020-05-18 18:31:35,209 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
